name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  # Permite que o pipeline de Infra chame este aqui assim que terminar
  workflow_run:
    workflows: ["Infraestrutura (Terraform)"]
    types:
      - completed

jobs:
  deploy-frontend:
    name: Upload Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # -----------------------------------------------------------
      # Ler os Outputs da Infraestrutura
      # -----------------------------------------------------------
      - name: Configurar AWS e Ler Infra
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform (Apenas para ler outputs)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Carregar Variaveis da Infra
        id: infra
        working-directory: ./terraform
        run: |
          terraform init
          echo "s3_bucket=$(terraform output -raw s3_frontend_bucket)" >> $GITHUB_OUTPUT
          echo "cloudfront_id=$(terraform output -raw cloudfront_frontend_distribution_id)" >> $GITHUB_OUTPUT

      # -----------------------------------------------------------
      # Deploy FRONTEND (estatico, sem build)
      # -----------------------------------------------------------
      - name: Upload Frontend para S3
        run: |
          aws s3 sync ./frontend s3://${{ steps.infra.outputs.s3_bucket }} --delete \
            --exclude "*" \
            --include "index.html" \
            --include "app.js" \
            --include "styles.css"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.infra.outputs.cloudfront_id }} \
            --paths "/*"

